# Generated by Django 3.0.7 on 2020-07-17 05:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200717_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 5, 48, 50, 444441, tzinfo=utc)),
        ),
    ]
